[tool.poetry]
name = "infill-video-cutter"
version = "0.1.0"
description = ""
authors = ["h.haeger <henrik.haeger@comma-soft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
